### ISSUE TITLE
Combobox in workflow definition is also hidden

### ISSUE THREAD

**Issue by dydimos** [alexwais/redmine_workflow_hidden_fields#1]
Hello,

first, thanks for this very useful plugin. I set some fields to state hidden in the workflow definition, as described and the fields are hidden in the new issue form as expected.

Unfortunately, the comboboxes in the workflow definition form to set the states are now also hidden for these fields. So, its not possible to change the hidden state after setting it once. 

Can you please fix this? :o)

Thanks

**Comment by tianyang-abc** [comment]
> I cannot reproduce this on my environment, but I guess it is a stylesheet issue.
> 
> The comboboxes are wrapped in a `<td class="hidden">` element, and probably your stylesheet defines elements with class 'hidden' as visibility: hidden or something similar.
> 
> Unfortunately the class value is generated automatically by Redmine, but a workaround would be to declare `table.list.fields_permissions td.hidden` elements as `visibility: visible!important`, for instance.

I counter the same missing Combobox in workflow. It's solved by following.
modify `application.css`, add
`#workflow_form td.hidden {display: unset;}`
