### ISSUE TITLE
Incompatible with redmine_issue_history

### ISSUE THREAD

**Issue by topkool** [alexwais/redmine_workflow_hidden_fields#10]
The plugin redmine_issue_history is reallyuseful as it split into 2 tabs the history and the comments, for a better readability.

However, once the pluging redmine_workflow_hidden_fields enabled, the history tab is empty, even for  a full permission user or the administrator

**Comment by alexwais** [comment]
there is no solution to resolve this conflict as both plugins overwrite the history template.
