### ISSUE TITLE
With Redmine 3.2, issue page is misdrawn

### ISSUE THREAD

**Issue by logirard** [alexwais/redmine_workflow_hidden_fields#13]
![screenshot](https://cloud.githubusercontent.com/assets/10209405/12299979/b63e31b0-ba19-11e5-8ab7-babe8c04fcd1.png)

The yellow area stops too early and other fields are written under the yellow area instead of inside it.

**Comment by logirard** [comment]
After some investigation, just modify *"<table"* by *"<div"* and *"</table"* by *"</div"* _in /app/views/issues/show.html.erb_ and the plugin works fine with Redmine 3.2.

**Comment by w0www** [comment]
Update this plugin with your solution please :)

**Comment by logirard** [comment]
All right, I emitted a "pull request" .

----- Mail original -----
De: "Imanol Alvarez Perez" <notifications@github.com>
À: "alexwais/redmine_workflow_hidden_fields" <redmine_workflow_hidden_fields@noreply.github.com>
Cc: "logirard" <laurent.girard1@libertysurf.fr>
Envoyé: Jeudi 21 Janvier 2016 10:49:52
Objet: Re: [redmine_workflow_hidden_fields] With Redmine 3.2, issue page is misdrawn (#13)



Update this plugin with your solution please :)

**Comment by alexwais** [comment]
Pull request merged.
