### ISSUE TITLE
workflow hidden fields are not working

### ISSUE THREAD

**Issue by sumantacaptain** [alexwais/redmine_workflow_hidden_fields#17]
Hi,

My redmine version - redmine-2.5.1
Hidden fields downloaded version - redmine_workflow_hidden_fields-0.1.2.1

I have downloaded it and paste it at redmine-2.5.1/plugins folder, but after restarting my server, redmine not starting. Should I run any migration/rake anything? 

Any help will be appreciated.

**Comment by alexwais** [comment]
Plugin is not compatible with Redmine 2.5.1.
