### ISSUE TITLE
Plugin crashes Redmine when loading an issue

### ISSUE THREAD

**Issue by ageis** [alexwais/redmine_workflow_hidden_fields#19]
Now running Redmine version 3.2.1, yet was originally was tracking the 3.2-stable branch from GitHub which has a few extra commits on top of that. Everything was working fine for quite a while and we were hiding a few workflow fields on issues, and then we started getting this error when loading any/every issue, while the service was in production, so we had to remove the plugin.

Although the bug only started presenting after a `git pull` on Redmine, that may only be a coincidence, as reverting back to 3.2.1 did not fix it. Nothing much else changed about our environment, nor settings in Redmine that I can note. So I don't have any ideas, but the problem is apparently in the plugin code, where you have a conditional or a loop that is not properly terminated. Would really like to see this fixed, so let me know if you need additional info.

```
Completed 500 Internal Server Error in 567ms (ActiveRecord: 120.1ms)

SyntaxError (/var/www/redmine/plugins/redmine_workflow_hidden_fields/app/views/issues/_history.html.erb:31: syntax error, unexpected keyword_ensure, expecting keyword_end
/var/www/redmine/plugins/redmine_workflow_hidden_fields/app/views/issues/_history.html.erb:33: syntax error, unexpected end-of-input, expecting keyword_end):
  plugins/redmine_workflow_hidden_fields/app/views/issues/_history.html.erb:31: syntax error, unexpected keyword_ensure, expecting keyword_end
  plugins/redmine_workflow_hidden_fields/app/views/issues/_history.html.erb:33: syntax error, unexpected end-of-input, expecting keyword_end
  plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb:174:in `_51abe8dbafb53150f5d08f16bbf0120f'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by xhervy** [comment]
I am experiencing exactly the same error using Redmine 3.2.1 as well

**Comment by ageis** [comment]
I'd like to add that one thing which may have triggered the bug is editing the title of an issue for the first time.

**Comment by xhervy** [comment]
Create an issue, then adding a note to it, is enough for me to reproduce the problem.
I can also create an issue and modified a custom field to reproduce the problem.

I will have a look at _history.html.erb later on, but I do not know ruby at all.

**Comment by xhervy** [comment]
Check out https://github.com/xhervy/redmine_workflow_hidden_fields for a possible fix
