### ISSUE TITLE
Feature: add 'Advance editing' permission

### ISSUE THREAD

**Issue by xhervy** [alexwais/redmine_workflow_hidden_fields#22]
Hi,

I am trying to add an additional permission on for fields and custom fields.

The **Advance editing** permission should display the fields as normal but will not be show by default in the edit form.
The fields  will be in the form but not display unless the user click on an **Advanced mode** button.

The idea behind this is to show only the relevant fields depending of the status of the tracker but still have the ability for the user to edit them if needed.

I am trying to implement this because in my use case I need to have a lot of custom fields which is a bit overwhelming for my users.

I started to implemented it:
- I modified the issue editing form to hide those fields by default.
- Added a button to toggle between advanced mode and basic mode
- I added the new permission so it is selectable in the **Work-flow - Permission fields** page.

My problem at the moment is that it does not save when I select 'Advance editing' for a custom fields. Any idea what I could be doing wrong ?

PS: new to ruby and redmine, this is quite a learning curve for me, any pointer would be appreciated

Xavier

**Comment by alexwais** [comment]
The described functionality is not in the scope of this plugin. Actually, it is not even supposed to be a 'permission'.
