### ISSUE TITLE
it seems not compatible with plugin redmine_spent_time_in_issue_description 

### ISSUE THREAD

**Issue by archonwang** [alexwais/redmine_workflow_hidden_fields#25]
@visagio , @alexwais 
it seems not compatible with plugin redmine_spent_time_in_issue_description (https://github.com/TravisSpangle/redmine_spent_time_in_issue_description)
if I installed the plugin, the redmine_spent_time_in_issue_description ould not display correctly. please check it. Thanks.

**Comment by alexwais** [comment]
Keeping compatibility with other plugins is out of scope.
