### ISSUE TITLE
Redmine 5.0 compatibility

### ISSUE THREAD

**Issue by mgcd-jed** [alexwais/redmine_workflow_hidden_fields#51]
Please consider making this compatible with redmine 5.0 :)

**Comment by gc-olivierho** [comment]
Hi,
I've published a Pull request for compatibility with Redmine 5.0. Feel free to use it, and of course, if you notice any issue with the changes, please comment this ticket.

**Comment by ghost** [comment]
@gc-olivierho Just tested it out and had no issues. Many thanks !
