### ISSUE TITLE
Issues list renders slowly after installing plugin

### ISSUE THREAD

**Issue by garett** [alexwais/redmine_workflow_hidden_fields#6]
First, great job on this plugin. We've found it very useful. One issue we've been encountering is that issues list across all projects in our Redmine installation renders slowly after installing the plugin. Once removed everything works fine. We are on Redmine 2.5.2.

**Comment by alexwais** [comment]
Hello, I'm aware of that problem and I could already fix it to improve performance. I'll publish the patch in the next days.

**Comment by garett** [comment]
Thanks, and great job!

**Comment by SimonK99** [comment]
Hi, Thanks for the great Plugin!
 
Is the Patch already published? We have big Performance Problems.

**Comment by alexwais** [comment]
fixed for redmine 3.0.1, thanks to AllTaken
